[project]
name = "obsidianautotag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "huggingface-hub>=0.27.1",
]

[dependency-groups]
dev = [
    "gputil>=1.4.0",
    "jupyter>=1.1.1",
]
